server:
  port: 9077
  servlet:
    context-path: /navigation
mybatis-plus:
  #打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #mybtais plus 会将pojo的驼峰命名转为下划线 导致和数据库里面字段不匹配 这里加上false就好了
    map-underscore-to-camel-case: true
  # 配置扫描xml
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.duzj.navigation.entity
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/navigation?serverTimezone=GMT&userSSL=false&characterEncoding=utf-8   #生产读写分离
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: MyHikariCP
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
